In [1]:
from xml.etree.ElementPath import prepare_descendant

import pandas as pd
import numpy as np
from nltk import extract_test_sentences
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

from Lesson05.IrisKNN import DataToPredict


In [2]:
names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [3]:
df = pd.read_csv('Iris.data.csv', header=None, names=names)
x = np.array(df.iloc[:,0:4])
y = np.array((df['class']))

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [5]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
pred = knn.predict(x_test)

In [6]:
print("Model accurancy score: ", accuracy_score(y_test, pred))
print("\nFrom the test data")
print('Index\tPredicted\t\tActual')
for i in range(len(pred)):
    if pred[i] != y_test[i]:
        print(i, '\t', pred[i], '\t', y_test[i], ' ****')

Model accurancy score:  0.9555555555555556

From the test data
Index	Predicted		Actual
14 	 Iris-versicolor 	 Iris-virginica  ****
27 	 Iris-versicolor 	 Iris-virginica  ****


In [7]:
DataToPredict = np.array([[5.2, 3.5, 1.4, 0.2], [5.7, 2.9, 3.6, 1.3], [5.8, 3.0, 5.1, 1.8]])
pred = knn.predict(DataToPredict)

In [8]:
print("Predicted Results")
for i in range(len(pred)):
    print('\t', DataToPredict[i], '\t', pred[i])

Predicted Results
	 [5.2 3.5 1.4 0.2] 	 Iris-setosa
	 [5.7 2.9 3.6 1.3] 	 Iris-versicolor
	 [5.8 3.  5.1 1.8] 	 Iris-virginica
